INSERT INTO PRODUCT VALUES (1, 'APPLE', 'IPHONE', 1200, 1, 'SMARTPHONE');
INSERT INTO PRODUCT VALUES (2, 'SAMSUNG', 'GALAXY S23', 1320, 1, 'TABLET');
INSERT INTO PRODUCT VALUES (3, 'ROLEX', 'OYSTER PERPETUAL', 120000, 1, 'LUXURY WATCH');
INSERT INTO PRODUCT VALUES (4, 'SONY', 'PS5', 700, 1, 'CONSOLE');
INSERT INTO PRODUCT VALUES (5, 'MODEL 3', 'TESLA', 3000, 1, 'ELETRIC CAR');
INSERT INTO PRODUCT VALUES (6, 'IDEA PAD 320', 'LENOVO', 400, 1, 'NOTEBOOK');